### ISSUE TITLE
PostgreSQL's regression tests fail after loading pg_ivm extension.

### ISSUE THREAD

**Issue by bytezzz** [sraoss/pg_ivm#77] opened 2023-11-06 15:07 UTC
I added pg_ivm as an preload libraries by setting `shared_preload_libraries = 'pg_ivm'`.

When I was trying to run PostgreSQL's regression test, about half of them will fail.

```
# using postmaster on Unix socket, default port
not ok 1     - test_setup                                338 ms
# parallel group (20 tests, in groups of 1):  boolean char name varchar text int2 int4 int8 oid float4 float8 bit numeric txid uuid enum money rangetypes pg_lsn regproc
not ok 2     + boolean                                    67 ms
not ok 3     + char                                       34 ms
not ok 4     + name                                       31 ms
not ok 5     + varchar                                    48 ms
ok 6         + text                                       62 ms
ok 7         + int2                                      102 ms
ok 8         + int4                                       90 ms
ok 9         + int8                                      108 ms
not ok 10    + oid                                        31 ms
ok 11        + float4                                     54 ms
not ok 12    + float8                                    101 ms
not ok 13    + bit                                       101 ms
not ok 14    + numeric                                   506 ms
not ok 15    + txid                                       25 ms
not ok 16    + uuid                                      106 ms
not ok 17    + enum                                      138 ms
ok 18        + money                                      73 ms
not ok 19    + rangetypes                                522 ms
not ok 20    + pg_lsn                                     33 ms
ok 21        + regproc                                    46 ms
# parallel group (20 tests, in groups of 1):  strings md5 numerology point lseg line box path polygon circle date time timetz timestamp timestamptz interval inet macaddr macaddr8 multirangetypes
not ok 22    + strings                                   302 ms
ok 23        + md5                                        19 ms
not ok 24    + numerology                                 56 ms
not ok 25    + point                                      52 ms
ok 26        + lseg                                       28 ms
ok 27        + line                                       43 ms
not ok 28    + box                                       199 ms
ok 29        + path                                       28 ms
not ok 30    + polygon                                   175 ms
ok 31        + circle                                     32 ms
ok 32        + date                                      127 ms
ok 33        + time                                       39 ms
ok 34        + timetz                                     42 ms
ok 35        + timestamp                                 527 ms
not ok 36    + timestamptz                               562 ms
not ok 37    + interval                                  172 ms
not ok 38    + inet                                      105 ms
not ok 39    + macaddr                                    63 ms
not ok 40    + macaddr8                                   81 ms
not ok 41    + multirangetypes                           418 ms
# parallel group (12 tests, in groups of 1):  geometry horology tstypes regex type_sanity opr_sanity misc_sanity comments expressions unicode xid mvcc
ok 42        + geometry                                  147 ms
not ok 43    + horology                                  252 ms
ok 44        + tstypes                                   104 ms
ok 45        + regex                                     368 ms
not ok 46    + type_sanity                               161 ms
ok 47        + opr_sanity                                361 ms
ok 48        + misc_sanity                                15 ms
ok 49        + comments                                   11 ms
ok 50        + expressions                                56 ms
ok 51        + unicode                                    14 ms
not ok 52    + xid                                        49 ms
ok 53        + mvcc                                       90 ms
# parallel group (5 tests, in groups of 1):  copy copyselect copydml insert insert_conflict
not ok 54    + copy                                      155 ms
not ok 55    + copyselect                                 43 ms
not ok 56    + copydml                                    91 ms
not ok 57    + insert                                    718 ms
not ok 58    + insert_conflict                           400 ms
# parallel group (7 tests, in groups of 1):  create_function_c create_misc create_operator create_procedure create_table create_type create_schema
ok 59        + create_function_c                          14 ms
ok 60        + create_misc                               147 ms
ok 61        + create_operator                            42 ms
not ok 62    + create_procedure                          127 ms
not ok 63    + create_table                              700 ms
not ok 64    + create_type                               111 ms
not ok 65    + create_schema                              66 ms
# parallel group (5 tests, in groups of 1):  create_index create_index_spgist create_view index_including index_including_gist
not ok 66    + create_index                             1282 ms
not ok 67    + create_index_spgist                       367 ms
not ok 68    + create_view                               387 ms
not ok 69    + index_including                           220 ms
not ok 70    + index_including_gist                      345 ms
# parallel group (16 tests, in groups of 1):  create_aggregate create_function_sql create_cast constraints triggers select inherit typed_table vacuum drop_if_exists updatable_views roleattributes create_am hash_func errors infinite_recurse
ok 71        + create_aggregate                           86 ms
not ok 72    + create_function_sql                       154 ms
ok 73        + create_cast                                47 ms
not ok 74    + constraints                               409 ms
not ok 75    + triggers                                 2302 ms
not ok 76    + select                                     73 ms
not ok 77    + inherit                                  1204 ms
not ok 78    + typed_table                               125 ms
not ok 79    + vacuum                                    532 ms
not ok 80    + drop_if_exists                            166 ms
not ok 81    + updatable_views                          1129 ms
ok 82        + roleattributes                            154 ms
not ok 83    + create_am                                 138 ms
not ok 84    + hash_func                                  69 ms
ok 85        + errors                                     40 ms
ok 86        + infinite_recurse                          275 ms
ok 87        - sanity_check                              352 ms
# parallel group (20 tests, in groups of 1):  select_into select_distinct select_distinct_on select_implicit select_having subselect union case join aggregates transactions random portals arrays btree_index hash_index update delete namespace prepared_xacts
not ok 88    + select_into                                68 ms
not ok 89    + select_distinct                           133 ms
ok 90        + select_distinct_on                         15 ms
not ok 91    + select_implicit                            43 ms
not ok 92    + select_having                              75 ms
not ok 93    + subselect                                 276 ms
not ok 94    + union                                     196 ms
not ok 95    + case                                       59 ms
not ok 96    + join                                      770 ms
not ok 97    + aggregates                                905 ms
not ok 98    + transactions                              298 ms
ok 99        + random                                     51 ms
not ok 100   + portals                                   205 ms
not ok 101   + arrays                                    435 ms
not ok 102   + btree_index                              1405 ms
not ok 103   + hash_index                                453 ms
not ok 104   + update                                    848 ms
not ok 105   + delete                                     49 ms
not ok 106   + namespace                                  52 ms
not ok 107   + prepared_xacts                             80 ms
# parallel group (20 tests, in groups of 1):  brin gin gist spgist privileges init_privs security_label collate matview lock replica_identity rowsecurity object_address tablesample groupingsets drop_operator password identity generated join_hash
not ok 108   + brin                                      568 ms
not ok 109   + gin                                       347 ms
not ok 110   + gist                                      933 ms
ok 111       + spgist                                    466 ms
not ok 112   + privileges                               1683 ms
ok 113       + init_privs                                 12 ms
not ok 114   + security_label                             72 ms
not ok 115   + collate                                   224 ms
not ok 116   + matview                                   506 ms
not ok 117   + lock                                      168 ms
not ok 118   + replica_identity                          301 ms
not ok 119   + rowsecurity                              1396 ms
not ok 120   + object_address                            195 ms
not ok 121   + tablesample                                92 ms
not ok 122   + groupingsets                              416 ms
ok 123       + drop_operator                              30 ms
ok 124       + password                                  160 ms
not ok 125   + identity                                  310 ms
not ok 126   + generated                                1137 ms
ok 127       + join_hash                               12027 ms
# parallel group (2 tests, in groups of 1):  brin_bloom brin_multi
ok 128       + brin_bloom                                181 ms
not ok 129   + brin_multi                                653 ms
# parallel group (16 tests, in groups of 1):  create_table_like alter_generic alter_operator misc async dbsize merge misc_functions sysviews tsrf tid tidscan tidrangescan collate.icu.utf8 incremental_sort create_role
not ok 130   + create_table_like                         581 ms
not ok 131   + alter_generic                             293 ms
ok 132       + alter_operator                             74 ms
not ok 133   + misc                                      173 ms
ok 134       + async                                      14 ms
ok 135       + dbsize                                     30 ms
not ok 136   + merge                                     617 ms
ok 137       + misc_functions                            373 ms
ok 138       + sysviews                                   72 ms
not ok 139   + tsrf                                      114 ms
not ok 140   + tid                                        86 ms
not ok 141   + tidscan                                    59 ms
not ok 142   + tidrangescan                               86 ms
not ok 143   + collate.icu.utf8                          956 ms
not ok 144   + incremental_sort                          169 ms
not ok 145   + create_role                               175 ms
# parallel group (7 tests, in groups of 1):  rules psql psql_crosstab amutils stats_ext collate.linux.utf8 collate.windows.win1252
not ok 146   + rules                                    1135 ms
not ok 147   + psql                                      844 ms
not ok 148   + psql_crosstab                              46 ms
not ok 149   + amutils                                    28 ms
not ok 150   + stats_ext                                5692 ms
ok 151       + collate.linux.utf8                         11 ms
ok 152       + collate.windows.win1252                    17 ms
not ok 153   - select_parallel                           157 ms
not ok 154   - write_parallel                             50 ms
ok 155       - vacuum_parallel                           194 ms
# parallel group (2 tests, in groups of 1):  publication subscription
not ok 156   + publication                              1690 ms
ok 157       + subscription                              199 ms
# parallel group (17 tests, in groups of 1):  select_views portals_p2 foreign_key cluster dependency guc bitmapops combocid tsearch tsdicts foreign_data window xmlmap functional_deps advisory_lock indirect_toast equivclass
ok 158       + select_views                              249 ms
ok 159       + portals_p2                                 29 ms
not ok 160   + foreign_key                              2240 ms
not ok 161   + cluster                                   803 ms
not ok 162   + dependency                                168 ms
not ok 163   + guc                                       100 ms
not ok 164   + bitmapops                                 407 ms
not ok 165   + combocid                                   39 ms
not ok 166   + tsearch                                   443 ms
ok 167       + tsdicts                                   101 ms
not ok 168   + foreign_data                             1360 ms
not ok 169   + window                                    493 ms
ok 170       + xmlmap                                     88 ms
not ok 171   + functional_deps                            29 ms
ok 172       + advisory_lock                              46 ms
not ok 173   + indirect_toast                            468 ms
not ok 174   + equivclass                                118 ms
# parallel group (7 tests, in groups of 1):  json jsonb json_encoding jsonpath jsonpath_encoding jsonb_jsonpath sqljson
not ok 175   + json                                      416 ms
not ok 176   + jsonb                                     826 ms
ok 177       + json_encoding                              25 ms
ok 178       + jsonpath                                  219 ms
ok 179       + jsonpath_encoding                          28 ms
ok 180       + jsonb_jsonpath                            239 ms
not ok 181   + sqljson                                   197 ms
# parallel group (18 tests, in groups of 1):  plancache limit plpgsql copy2 temp domain rangefuncs prepare conversion truncate alter_table sequence polymorphism rowtypes returning largeobject with xml
not ok 182   + plancache                                  84 ms
not ok 183   + limit                                     195 ms
not ok 184   + plpgsql                                  2798 ms
not ok 185   + copy2                                     287 ms
not ok 186   + temp                                      227 ms
not ok 187   + domain                                    813 ms
not ok 188   + rangefuncs                                523 ms
not ok 189   + prepare                                    67 ms
ok 190       + conversion                                274 ms
not ok 191   + truncate                                  530 ms
not ok 192   + alter_table                              4292 ms
not ok 193   + sequence                                  435 ms
not ok 194   + polymorphism                              605 ms
not ok 195   + rowtypes                                  378 ms
not ok 196   + returning                                  93 ms
not ok 197   + largeobject                               278 ms
not ok 198   + with                                      258 ms
ok 199       + xml                                       213 ms
# parallel group (12 tests, in groups of 1):  partition_join partition_prune reloptions hash_part indexing partition_aggregate partition_info tuplesort explain compression memoize stats
not ok 200   + partition_join                           2109 ms
not ok 201   + partition_prune                          1547 ms
not ok 202   + reloptions                                 94 ms
not ok 203   + hash_part                                  75 ms
not ok 204   + indexing                                 2651 ms
ok 205       + partition_aggregate                       725 ms
not ok 206   + partition_info                             83 ms
not ok 207   + tuplesort                                  33 ms
not ok 208   + explain                                   409 ms
not ok 209   + compression                               186 ms
not ok 210   + memoize                                   157 ms
not ok 211   + stats                                    2557 ms
# parallel group (2 tests, in groups of 1):  event_trigger oidjoins
not ok 212   + event_trigger                             521 ms
ok 213       + oidjoins                                  454 ms
not ok 214   - fast_default                              941 ms
not ok 215   - tablespace                               1211 ms
1..215
# 151 of 215 tests failed.
```

**Comment by yugo-n** [comment] 2023-12-22 03:11
Thank you for the report.
The cause of error would be that you installed pg_ivm using shared_preload_libraries instead of CREATE EXTENSION because the former doesn't create catalog tables referred to in the hook function.

**Comment by yugo-n** [comment] 2024-03-01 05:15
@bytezzz 
I merged your PR. Thanks!

**Closed** 2024-03-01 05:15 UTC
